Preamble

In [1]:
# -*- coding: utf-8 -*-


import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
import scipy.stats as stats
import seaborn as sns

import statsmodels.api as sm



# for regression
import statsmodels.formula.api as smf
from sklearn import datasets
from statistics import mean



/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


Read Data, DU

In [2]:
#Read the data, modified USCrime data

data=pd.read_csv('UScrime 2.csv')

print(data.shape)
print(list(data.columns))

X = data.loc[:, data.columns != 'Crime']
y = data.loc[:, data.columns == 'Crime']
X=sm.add_constant(X)

y

(47, 14)
['M', 'So', 'Ed', 'Po1', 'LF', 'MF', 'Pop', 'NW', 'U1', 'Wealth', 'Ineq', 'Prob', 'Time', 'Crime']


Crime
0     791
1    1635
2     578
3    1969
4    1234
5     682
6     963
7    1555
8     856
9     705
10   1674
11    849
12    511
13    664
14    798
15    946
16    539
17    929
18    750
19   1225
20    742
21    439
22   1216
23    968
24    523
25   1993
26    342
27   1216
28   1043
29    696
30    373
31    754
32   1072
33    923
34    653
35   1272
36    831
37    566
38    826
39   1151
40    880
41    542
42    823
43   1030
44    455
45    508
46    849

DU2

In [3]:
X

const     M  So    Ed   Po1     LF     MF  Pop    NW     U1  Wealth  Ineq      Prob     Time
0     1.0  15.1   1   9.1   5.8  0.510   95.0   33  30.1  0.108    3940  26.1  0.084602  26.2011
1     1.0  14.3   0  11.3  10.3  0.583  101.2   13  10.2  0.096    5570  19.4  0.029599  25.2999
2     1.0  14.2   1   8.9   4.5  0.533   96.9   18  21.9  0.094    3180  25.0  0.083401  24.3006
3     1.0  13.6   0  12.1  14.9  0.577   99.4  157   8.0  0.102    6730  16.7  0.015801  29.9012
4     1.0  14.1   0  12.1  10.9  0.591   98.5   18   3.0  0.091    5780  17.4  0.041399  21.2998
5     1.0  12.1   0  11.0  11.8  0.547   96.4   25   4.4  0.084    6890  12.6  0.034201  20.9995
6     1.0  12.7   1  11.1   8.2  0.519   98.2    4  13.9  0.097    6200  16.8  0.042100  20.6993
7     1.0  13.1   1  10.9  11.5  0.542   96.9   50  17.9  0.079    4720  20.6  0.040099  24.5988
8     1.0  15.7   1   9.0   6.5  0.553   95.5   39  28.6  0.081    4210  23.9  0.071697  29.4001
9     1.0  14.0   0  11.8   7.1  0.632  102.9    7   1.5  0.100    5260  17.4  0.044498  19.5994
10    1.0  12.4   0  10.5  12.1  0.580   96.6  101  10.6  0.077    6570  17.0  0.016201  41.6000
11    1.0  13.4   0  10.8   7.5  0.595   97.2   47   5.9  0.083    5800  17.2  0.031201  34.2984
12    1.0  12.8   0  11.3   6.7  0.624   97.2   28   1.0  0.077    5070  20.6  0.045302  36.2993
13    1.0  13.5   0  11.7   6.2  0.595   98.6   22   4.6  0.077    5290  19.0  0.053200  21.5010
14    1.0  15.2   1   8.7   5.7  0.530   98.6   30   7.2  0.092    4050  26.4  0.069100  22.7008
15    1.0  14.2   1   8.8   8.1  0.497   95.6   33  32.1  0.116    4270  24.7  0.052099  26.0991
16    1.0  14.3   0  11.0   6.6  0.537   97.7   10   0.6  0.114    4870  16.6  0.076299  19.1002
17    1.0  13.5   1  10.4  12.3  0.537   97.8   31  17.0  0.089    6310  16.5  0.119804  18.1996
18    1.0  13.0   0  11.6  12.8  0.536   93.4   51   2.4  0.078    6270  13.5  0.019099  24.9008
19    1.0  12.5   0  10.8  11.3  0.567   98.5   78   9.4  0.130    6260  16.6  0.034801  26.4010
20    1.0  12.6   0  10.8   7.4  0.602   98.4   34   1.2  0.102    5570  19.5  0.022800  37.5998
21    1.0  15.7   1   8.9   4.7  0.512   96.2   22  42.3  0.097    2880  27.6  0.089502  37.0994
22    1.0  13.2   0   9.6   8.7  0.564   95.3   43   9.2  0.083    5130  22.7  0.030700  25.1989
23    1.0  13.1   0  11.6   7.8  0.574  103.8    7   3.6  0.142    5400  17.6  0.041598  17.6000
24    1.0  13.0   0  11.6   6.3  0.641   98.4   14   2.6  0.070    4860  19.6  0.069197  21.9003
25    1.0  13.1   0  12.1  16.0  0.631  107.1    3   7.7  0.102    6740  15.2  0.041698  22.1005
26    1.0  13.5   0  10.9   6.9  0.540   96.5    6   0.4  0.080    5640  13.9  0.036099  28.4999
27    1.0  15.2   0  11.2   8.2  0.571  101.8   10   7.9  0.103    5370  21.5  0.038201  25.8006
28    1.0  11.9   0  10.7  16.6  0.521   93.8  168   8.9  0.092    6370  15.4  0.023400  36.7009
29    1.0  16.6   1   8.9   5.8  0.521   97.3   46  25.4  0.072    3960  23.7  0.075298  28.3011
30    1.0  14.0   0   9.3   5.5  0.535  104.5    6   2.0  0.135    4530  20.0  0.041999  21.7998
31    1.0  12.5   0  10.9   9.0  0.586   96.4   97   8.2  0.105    6170  16.3  0.042698  30.9014
32    1.0  14.7   1  10.4   6.3  0.560   97.2   23   9.5  0.076    4620  23.3  0.049499  25.5005
33    1.0  12.6   0  11.8   9.7  0.542   99.0   18   2.1  0.102    5890  16.6  0.040799  21.6997
34    1.0  12.3   0  10.2   9.7  0.526   94.8  113   7.6  0.124    5720  15.8  0.020700  37.4011
35    1.0  15.0   0  10.0  10.9  0.531   96.4    9   2.4  0.087    5590  15.3  0.006900  44.0004
36    1.0  17.7   1   8.7   5.8  0.638   97.4   24  34.9  0.076    3820  25.4  0.045198  31.6995
37    1.0  13.3   0  10.4   5.1  0.599  102.4    7   4.0  0.099    4250  22.5  0.053998  16.6999
38    1.0  14.9   1   8.8   6.1  0.515   95.3   36  16.5  0.086    3950  25.1  0.047099  27.3004
39    1.0  14.5   1  10.4   8.2  0.560   98.1   96  12.6  0.088    4880  22.8  0.038801  29.3004
40    1.0  14.8   0  12.2  

Create LR model

In [4]:
model = smf.ols('y ~ M + So + Ed + Po1 + LF + MF + Pop + NW + U1 + Wealth + Ineq + Prob + Time', data=data).fit()

# model = smf.ols('y ~ M + Ed + Po1 + Wealth + Ineq + Prob ', data=data).fit()

predictions = model.predict(X) 

print_model = model.summary()
print(print_model)


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.771
Model:                            OLS   Adj. R-squared:                  0.680
Method:                 Least Squares   F-statistic:                     8.531
Date:                Thu, 18 Nov 2021   Prob (F-statistic):           3.35e-07
Time:                        18:59:19   Log-Likelihood:                -311.59
No. Observations:                  47   AIC:                             651.2
Df Residuals:                      33   BIC:                             677.1
Df Model:                          13                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -5627.8024   1599.428     -3.519      0.0

Model 1

In [5]:
###  Build Every Possible Model
from itertools import chain, combinations

def powerset(iterable):
    s=list(iterable)
    return chain.from_iterable(combinations(s,r) for r in range(1, len(s)+1))
    
mylist=list(powerset(list(X.columns)))
mylist=[list(row) for row in mylist]

print(mylist)

[['const'], ['M'], ['So'], ['Ed'], ['Po1'], ['LF'], ['MF'], ['Pop'], ['NW'], ['U1'], ['Wealth'], ['Ineq'], ['Prob'], ['Time'], ['const', 'M'], ['const', 'So'], ['const', 'Ed'], ['const', 'Po1'], ['const', 'LF'], ['const', 'MF'], ['const', 'Pop'], ['const', 'NW'], ['const', 'U1'], ['const', 'Wealth'], ['const', 'Ineq'], ['const', 'Prob'], ['const', 'Time'], ['M', 'So'], ['M', 'Ed'], ['M', 'Po1'], ['M', 'LF'], ['M', 'MF'], ['M', 'Pop'], ['M', 'NW'], ['M', 'U1'], ['M', 'Wealth'], ['M', 'Ineq'], ['M', 'Prob'], ['M', 'Time'], ['So', 'Ed'], ['So', 'Po1'], ['So', 'LF'], ['So', 'MF'], ['So', 'Pop'], ['So', 'NW'], ['So', 'U1'], ['So', 'Wealth'], ['So', 'Ineq'], ['So', 'Prob'], ['So', 'Time'], ['Ed', 'Po1'], ['Ed', 'LF'], ['Ed', 'MF'], ['Ed', 'Pop'], ['Ed', 'NW'], ['Ed', 'U1'], ['Ed', 'Wealth'], ['Ed', 'Ineq'], ['Ed', 'Prob'], ['Ed', 'Time'], ['Po1', 'LF'], ['Po1', 'MF'], ['Po1', 'Pop'], ['Po1', 'NW'], ['Po1', 'U1'], ['Po1', 'Wealth'], ['Po1', 'Ineq'], ['Po1', 'Prob'], ['Po1', 'Time'], ['LF', 'M

Analysis - AIC & BIC

In [6]:
##Target is AIC
AIC_scores=pd.DataFrame(columns=["AIC"])
for i in range(len(mylist)):
    AIC_scores.loc[i,'AIC']=sm.OLS(y,X[mylist[i]]).fit().aic
    
print(AIC_scores.sort_values(by='AIC').head(50))



#             AIC
# 6885   641.154
# 6851   641.208
# 10456  641.235
# 3670   641.464
# 10476  641.626

mylist[6885]


# Out[6]: ['const', 'M', 'Ed', 'Po1', 'Wealth', 'Ineq', 'Prob']
# mylist[6851]
# Out[7]: ['const', 'M', 'Ed', 'Po1', 'M.F', 'Ineq', 'Prob']
# mylist[10456]
# Out[8]: ['const', 'M', 'Ed', 'Po1', 'M.F', 'Wealth', 'Ineq', 'Prob']
# mylist[3670]
# Out[9]: ['const', 'M', 'Ed', 'Po1', 'Ineq', 'Prob']
# mylist[10476]
# Out[10]: ['const', 'M', 'Ed', 'Po1', 'Pop', 'Wealth', 'Ineq', 'Prob']

           AIC
6885   641.154
6851   641.208
10456  641.235
3670   641.464
10476  641.626
10490  641.747
9953   641.902
6882    642.08
6866   642.204
13487  642.333
12997  642.392
13403   642.71
13458  642.713
10494  642.762
10387  642.791
13468  642.803
9987   642.859
13472  642.873
6508   642.888
10437  642.901
10447  642.924
10473  642.924
10453  642.927
10486  643.062
10421  643.077
9984   643.144
13031  643.183
6888   643.198
10459  643.202
13476  643.228
13017  643.307
13483  643.379
6830   643.438
6876   643.443
13423  643.486
12994  643.534
13497  643.563
9968   643.579
13491  643.599
13492  643.606
12978  643.683
13437  643.743
15027  643.749
12928   643.81
12988  643.859
3667   643.869
13000  643.884
7313   643.915
13014  643.943
15012  643.962


['const', 'M', 'Ed', 'Po1', 'Wealth', 'Ineq', 'Prob']

BIC analysis

In [7]:
##Target is BIC
BIC_scores=pd.DataFrame(columns=["BIC"])
for i in range(len(mylist)):
    BIC_scores.loc[i,'BIC']=sm.OLS(y,X[mylist[i]]).fit().bic
    
print(BIC_scores.sort_values(by='BIC').head(50))

mylist[3670]
#            BIC
# 3670   652.565
# 6885   654.105
# 6851   654.159
# 3667    654.97
# 1531   655.001
# 6882   655.031
# 1888   655.102

           BIC
3670   652.565
6885   654.105
6851   654.159
3667    654.97
1531   655.001
6882   655.031
1888   655.102
6866   655.155
6508   655.839
4343   655.863
10456  656.036
6888   656.149
596    656.315
6830   656.389
6876   656.394
10476  656.427
4358    656.46
10490  656.549
9953   656.703
7313   656.866
2021   656.933
3649   657.124
3803   657.239
4000   657.277
6848   657.409
10494  657.563
10387  657.592
6879   657.594
9987    657.66
3664   657.678
7807   657.697
10437  657.702
1867   657.712
10447  657.725
10473  657.726
10453  657.728
4368    657.83
10486  657.863
3671   657.866
10421  657.878
9984   657.945
10459  658.004
7102   658.251
4377   658.273
4344   658.342
6886   658.364
6863   658.377
9968    658.38
3660   658.474
6852   658.494


['const', 'M', 'Ed', 'Po1', 'Ineq', 'Prob']

In [8]:
len(mylist)
mylist[3670]

['const', 'M', 'Ed', 'Po1', 'Ineq', 'Prob']

Stepwise Selection - Select K-best - only for classification tasks

In [9]:
#### Select K Best
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

# feature extraction
test = SelectKBest(score_func=f_regression, k=7)
fit = test.fit(X, y)

# summarize scores
np.set_printoptions(precision=3)
print(fit.scores_)
features = fit.transform(X)


# summarize selected features
print(features[0:5,:])

#Selected Ed, Po1, LF, MF, NW, Wealth, prob



[   nan  0.363  0.373  5.236 40.357  1.665  2.158  5.784  0.048  0.115
 10.884  1.49  10.059  1.034]
[[9.100e+00 5.800e+00 5.100e-01 9.500e+01 3.300e+01 3.940e+03 8.460e-02]
 [1.130e+01 1.030e+01 5.830e-01 1.012e+02 1.300e+01 5.570e+03 2.960e-02]
 [8.900e+00 4.500e+00 5.330e-01 9.690e+01 1.800e+01 3.180e+03 8.340e-02]
 [1.210e+01 1.490e+01 5.770e-01 9.940e+01 1.570e+02 6.730e+03 1.580e-02]
 [1.210e+01 1.090e+01 5.910e-01 9.850e+01 1.800e+01 5.780e+03 4.140e-02]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:985: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:289: RuntimeWarning: divide by zero encountered in true_divide
  correlation_coefficient /= X_norms
/usr/local/lib/python3.7/dist-packages/sklearn/feature_selection/_univariate_selection.py:358: RuntimeWarning: invalid value encountered in true_divide
  f_statistic = corr_coef_squared / (1 - corr_coef_squared) * deg_of_freedom


Recursive Feature Elimination

In [11]:
###  Recursive Feature Elimination

from sklearn.feature_selection import RFE
from sklearn import linear_model
model = linear_model.LinearRegression()

numberOfFeaturesToSelect = 5

# rfe = RFE(model, numberOfFeaturesToSelect)
rfe = RFE(estimator = model, n_features_to_select = numberOfFeaturesToSelect)
fit = rfe.fit(X, y)

f = fit.get_support(1) #the most important features
# final_features = data[data.columns[f]] # final features: this gives wrong results
final_features = X[X.columns[f]] # final features

print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % final_features.columns)
print("Score: %2.3f" % fit.score(X,y))

print("----------")

#Selected 'Ed', 'LF', 'MF', 'Wealth', 'Time'

# summarize all features
for i in range(X.shape[1]):
	print('Column: %d, %s, Selected %s, Rank: %.3f' % (i, X.columns.values[i],rfe.support_[i], rfe.ranking_[i]))
 

Num Features: 5
Selected Features: Index(['So', 'Po1', 'LF', 'U1', 'Prob'], dtype='object')
Score: 0.617
----------
Column: 0, const, Selected False, Rank: 10.000
Column: 1, M, Selected False, Rank: 2.000
Column: 2, So, Selected True, Rank: 1.000
Column: 3, Ed, Selected False, Rank: 3.000
Column: 4, Po1, Selected True, Rank: 1.000
Column: 5, LF, Selected True, Rank: 1.000
Column: 6, MF, Selected False, Rank: 5.000
Column: 7, Pop, Selected False, Rank: 7.000
Column: 8, NW, Selected False, Rank: 8.000
Column: 9, U1, Selected True, Rank: 1.000
Column: 10, Wealth, Selected False, Rank: 9.000
Column: 11, Ineq, Selected False, Rank: 4.000
Column: 12, Prob, Selected True, Rank: 1.000
Column: 13, Time, Selected False, Rank: 6.000


Model the result

In [12]:
# model = smf.ols('y ~ Prob', data=data).fit()  # best 1
# model = smf.ols('y ~ Prob + U1', data=data).fit()   # best 2
model = smf.ols('y ~ So + Po1 + LF + U1 + Prob', data=data).fit()   # best 5

predictions = model.predict(X) 

print_model = model.summary()
print(print_model)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.617
Model:                            OLS   Adj. R-squared:                  0.570
Method:                 Least Squares   F-statistic:                     13.21
Date:                Thu, 18 Nov 2021   Prob (F-statistic):           1.10e-07
Time:                        19:08:54   Log-Likelihood:                -323.65
No. Observations:                  47   AIC:                             659.3
Df Residuals:                      41   BIC:                             670.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept  -1821.4528    823.695     -2.211      0.0

RFE iteration

In [14]:
model = linear_model.LinearRegression()


print("\nSearch the best k features for k = 1 to 12\n")

for k in range(1, 12):
  # rfe = RFE(model, k)
  rfe = RFE(estimator = model, n_features_to_select = k)

  fit = rfe.fit(X, y) 

  f = fit.get_support(1) #the most important features

  # final_features = data[data.columns[f]] # final features: this gives wrong results
  final_features = X[X.columns[f]] # final features

  print("Num Features: %d" % fit.n_features_)
  print("Selected Features: %s" % final_features.columns)
  print("Score: %2.2f" % fit.score(X,y))
  print("----------")



Search the best k features for k = 1 to 12

Num Features: 1
Selected Features: Index(['Prob'], dtype='object')
Score: 0.18
----------
Num Features: 2
Selected Features: Index(['U1', 'Prob'], dtype='object')
Score: 0.19
----------
Num Features: 3
Selected Features: Index(['LF', 'U1', 'Prob'], dtype='object')
Score: 0.19
----------
Num Features: 4
Selected Features: Index(['So', 'LF', 'U1', 'Prob'], dtype='object')
Score: 0.24
----------
Num Features: 5
Selected Features: Index(['So', 'Po1', 'LF', 'U1', 'Prob'], dtype='object')
Score: 0.62
----------
Num Features: 6
Selected Features: Index(['M', 'So', 'Po1', 'LF', 'U1', 'Prob'], dtype='object')
Score: 0.66
----------
Num Features: 7
Selected Features: Index(['M', 'So', 'Ed', 'Po1', 'LF', 'U1', 'Prob'], dtype='object')
Score: 0.68
----------
Num Features: 8
Selected Features: Index(['M', 'So', 'Ed', 'Po1', 'LF', 'U1', 'Ineq', 'Prob'], dtype='object')
Score: 0.75
----------
Num Features: 9
Selected Features: Index(['M', 'So', 'Ed', 'Po1'